name: eabenchmark
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-delayedarray=0.20.0
  - bioconductor-genomeinfodb=1.30.1
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicranges=1.46.1
  - bioconductor-iranges=2.28.0
  - bioconductor-limma=3.50.1
  - bioconductor-matrixgenerics=1.6.0
  - bioconductor-s4vectors=0.32.4
  - bioconductor-summarizedexperiment=1.24.0
  - bioconductor-xvector=0.34.0
  - bioconductor-zlibbioc=1.40.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - cctools_osx-64=973.0.1
  - clang=14.0.6
  - clang-14=14.0.6
  - clang_osx-64=14.0.6
  - clangxx=14.0.6
  - clangxx_osx-64=14.0.6
  - compiler-rt=14.0.6
  - compiler-rt_osx-64=14.0.6
  - curl=7.86.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - gfortran_impl_osx-64=9.5.0
  - gfortran_osx-64=9.5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=3.1.1
  - icu=68.2
  - isl=0.25
  - jpeg=9e
  - krb5=1.19.3
  - ld64_osx-64=609
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp14=14.0.6
  - libcurl=7.86.0
  - libcxx=16.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.5.0
  - libgfortran5=13.2.0
  - libglib=2.74.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libssh2=1.11.0
  - libtiff=4.4.0
  - libwebp-base=1.3.2
  - libxml2=2.9.12
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - llvm-tools=14.0.6
  - make=4.3
  - mpc=1.3.1
  - mpfr=4.2.0
  - ncurses=6.4
  - openssl=3.1.3
  - pandoc=2.19.2
  - pango=1.48.10
  - pcre2=10.37
  - pixman=0.40.0
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.0
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-bookdown=0.26
  - r-broom=1.0.5
  - r-bslib=0.5.0
  - r-cachem=1.0.8
  - r-callr=3.7.3
  - r-cellranger=1.1.0
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-curl=4.3.3
  - r-data.table=1.14.8
  - r-dbi=1.1.3
  - r-dbplyr=2.3.2
  - r-digest=0.6.31
  - r-dosnow=1.0.20
  - r-dplyr=1.1.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.21
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-fs=1.6.2
  - r-gargle=1.4.0
  - r-generics=0.1.3
  - r-getopt=1.20.3
  - r-ggplot2=3.4.2
  - r-ggridges=0.5.4
  - r-glue=1.6.2
  - r-googledrive=2.1.0
  - r-googlesheets4=1.1.0
  - r-gtable=0.3.3
  - r-haven=2.5.2
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.5
  - r-httr=1.4.6
  - r-ids=1.0.1
  - r-igraph=1.3.0
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.5
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-lattice=0.21_8
  - r-lifecycle=1.0.3
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-mass=7.3_58.3
  - r-matrix=1.5_4.1
  - r-matrixstats=1.0.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_42
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_162
  - r-openssl=2.0.6
  - r-optparse=1.7.3
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.8
  - r-prettyunits=1.1.1
  - r-processx=3.8.1
  - r-progress=1.2.2
  - r-ps=1.7.5
  - r-purrr=1.0.1
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.10
  - r-rcurl=1.98_1.12
  - r-readr=2.1.4
  - r-readxl=1.4.2
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.2
  - r-reshape2=1.4.4
  - r-rlang=1.1.1
  - r-rmarkdown=2.22
  - r-rstudioapi=0.14
  - r-rvest=1.0.3
  - r-sass=0.4.6
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-snow=0.4_4
  - r-stringi=1.7.6
  - r-stringr=1.5.0
  - r-sys=3.4.2
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidyverse=1.3.2
  - r-timechange=0.2.0
  - r-tinytex=0.45
  - r-tzdb=0.4.0
  - r-utf8=1.2.3
  - r-uuid=1.1_0
  - r-vctrs=0.6.2
  - r-viridislite=0.4.1
  - r-vroom=1.6.3
  - r-withr=2.5.0
  - r-xfun=0.39
  - r-xml2=1.3.3
  - r-yaml=2.3.7
  - readline=8.2
  - sigtool=0.1.3
  - tapi=1100.0.11
  - tk=8.6.13
  - tktable=2.10
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
